---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logger
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
        - image: "dm848/srv-logger:v1"
          imagePullPolicy: Always
          name: logger
          ports:
            - containerPort: 8888
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: logger
  namespace: "default"
  labels:
    app: logger
spec:
  ports:
    - protocol: "TCP"
      port: 8888
      targetPort: 8888
  selector:
    app: logger
